// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obeabrdrtlxhucegkkiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iZWFicmRydGx4aHVjZWdra2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTE3MzUsImV4cCI6MjA2NTEyNzczNX0.V3ef9FfRjsQCTbRXihEaZrj4jC23JV2-s9Vaa2KndNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});